
WIDTH = 800
HEIGHT = 600
CENTER = (WIDTH // 2, HEIGHT//2)
SIZE_SCREEN = (WIDTH,HEIGHT)

FPS = 60
HOMER_SPEED = 15
DONA_SPEED = 5

SIZE_ICON = (32,32)
ORIGIN = (0,0)
HOMERO_SIZE = (150,200)
DONUT_SIZE = (70,70)

SCORE_POS = (50,50)

DISPLAY_TOP = 0
DISPLAY_BOTTOM = HEIGHT
DISPLAY_LEFT = 0
DISPLAY_RIGHT = WIDTH
DISPLAY_CENTER_X = WIDTH //2
DISPLAY_CENTER_Y = HEIGHT //2
DISPLAY_MIDTOP = (DISPLAY_CENTER_X,DISPLAY_TOP)

CENTER_X = WIDTH //2

RED = (255,0,0)
GREEN = (0, 255, 0)


